"""create_refueling_table_manual

Revision ID: 123456789abc
Revises:
Create Date: 2024-01-20 10:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "123456789abc"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "refuelings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("id_posto", sa.Integer(), nullable=False),
        sa.Column("data_hora", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "tipo_combustivel",
            sa.Enum("GASOLINA", "ETANOL", "DIESEL", name="fueltype"),
            nullable=False,
        ),
        sa.Column("preco_por_litro", sa.Float(), nullable=False),
        sa.Column("volume_abastecido", sa.Float(), nullable=False),
        sa.Column("cpf_motorista", sa.String(), nullable=False),
        sa.Column("improper_data", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_refuelings_cpf_motorista"),
        "refuelings",
        ["cpf_motorista"],
        unique=False,
    )
    op.create_index(op.f("ix_refuelings_id"), "refuelings", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_refuelings_id"), table_name="refuelings")
    op.drop_index(op.f("ix_refuelings_cpf_motorista"), table_name="refuelings")
    op.drop_table("refuelings")
    sa.Enum(name="fueltype").drop(op.get_bind())
    # ### end Alembic commands ###
